Add Aqua to the Tests plugin
JuliaCI/PkgTemplates.jl pull request #415
Opened 2023-07-31 20:59 UTC by gdalle

Solves #411 by adding a boolean field named `aqua` to the `Tests` plugin.
When it is set to `true`:

- Aqua is added as a test-specific dependency, either in `Project.toml` or `test/Project.toml`

- The file `test/runtests.jl` is modified to look like this:
```julia
using WackyOptions
using Test, Aqua

@testset "WackyOptions.jl" begin
    # Write your tests here.
    @testset verbose = true "Code quality (Aqua.jl)" begin
        Aqua.test_all(WackyOptions)
    end
end
```

If this is approved, I would like to do the same for other standard test tools (JET and JuliaFormatter, once #412 is merged).
I can either add them to this PR or put them in another one.

A few doubts I have:

- The templating behavior in `templates/test/runtests.jl` is not very elegant. Basically I put the placeholders at the end to avoid creating useless empty lines.
- As you can see from the `test/fixtures/WackyOptions/test/Manifest.toml` diff, Aqua is the first dependency that is not from the standard library. So whenever Aqua releases a new stable release, the reference tests will break because `Pkg.add("Aqua")` will pick the latest one. No sure how to future-proof that.
- There is nowhere I can test this with `project=false`, so I'm not entirely sure I got the mechanics of test-specific dependencies in the main `Project.toml` completely right.

2023-08-07 00:20 UTC, hannahilea commented on src/plugins/tests.jl
> +    aqua::Bool = false
Thanks for adding this! 

In many of my projects, I set aqua but with a different set of default kwargs (often `ambiguities=false`). Perhaps we could add an additional field to the `Tests` struct that allows a user to set those kwargs up front? 
e.g., 
```suggestion
    aqua::Bool = false
    aqua_kwarg_str::String = ""
```
and then (below)
```
kwargs = isempty(p.aqua_kwarg_str) ? "" : "; $(p.aqua_kwarg_str)"
Aqua.test_all($pkg$kwargs)
```

(or a sleeker version that passes the params through as a NamedTuple! But this easy version would be sufficient for my needs)

2023-08-07 06:45 UTC, gdalle commented on src/plugins/tests.jl
> +    aqua::Bool = false
done in the next commit :)

2023-08-07 08:11 UTC, gdalle commented
Beware that I removed Manifest comparison to ensure that non standard dependencies like Aqua can release new versions without breaking the PlgTemplates test pipeline. Is there a better way?

2023-08-07 13:42 UTC, hannahilea commented on src/plugins/tests.jl
> +    aqua::Bool = false
thanks!

2023-08-10 16:49 UTC, nickrobinson251 commented
hey, thanks for this! i don't have time to review right now. i wonder if @hannahilea would be happy to review this one to completion?

2023-08-13 13:43 UTC, hannahilea commented
sorry, i've been on vacation---i'll be back and happy to review this on wednesday if no one gets to it first!

2023-08-14 06:57 UTC, gdalle commented
No one has to apologize for being on vacation! Enjoy the rest of it, there is no rush

2023-08-19 04:23 UTC, hannahilea requested changes
This looks great!

I added a couple style preferences for ordering in the resultant runtests.jl file---feel free to ignore those.

> Beware that I removed Manifest comparison to ensure that non standard dependencies like Aqua can release new versions without breaking the PlgTemplates test pipeline. Is there a better way?

What if instead of the `aqua` kwarg, we instead use a `aqua_version` kwarg, with options `nothing` (don't use Aqua), `"*"` (use latest version of Aqua), or `v"0.6.2"` (set a compat bound equal to the provided version number)? I added suggestions to this affect---if you'd prefer not to do this, another option could be to add an additional kwarg that sets the version, so that (again) the version could be fixed for the manifest testing.

I have some ideas for testing the otherwise-untested code paths, but those will have to wait for tomorrow.

2023-08-19 04:23 UTC, hannahilea commented on src/plugins/tests.jl
> +        with_project(() -> Pkg.add(AQUA_DEP), joinpath(pkg_dir, "test"))
```suggestion
        with_project(() -> Pkg.add(; AQUA_DEP.name, AQUA_DEP.uuid, version=p.aqua_version), joinpath(pkg_dir, "test"))
```

2023-08-19 04:23 UTC, hannahilea commented on src/plugins/tests.jl
> +    end
```suggestion
    if !isnothing(p.aqua)
        get!(toml, "extras", Dict())["Aqua"] = AQUA_UUID
    end
    if p.aqua isa VersionNumber
        get!(toml, "compat", Dict())["Aqua"] = "=$(p.aqua)"
    end
```

2023-08-19 04:23 UTC, hannahilea commented on src/plugins/tests.jl
> +    get!(toml, "targets", Dict())["test"] = p.aqua ? ["Aqua", "Test"] : ["Test"]
```suggestion
    get!(toml, "targets", Dict())["test"] = isnothing(p.aqua) ? ["Test"] : ["Aqua", "Test"]
```

2023-08-19 04:23 UTC, hannahilea commented on test/reference.jl
> +                # Don't check Manifest: versions of packages like Aqua may vary
```suggestion
```
...and can also remove corresponding `end`. If you choose to make `p.aqua` include the aqua version used (or otherwise pass version in), we can set the version in the test and then continue to test the manifest.

2023-08-19 04:23 UTC, hannahilea commented on test/reference.jl
> +                aqua=true,
```suggestion
                aqua_version=v"0.6.5",
```
to fix it so that the manifest doesn't change!

2023-08-19 04:23 UTC, hannahilea commented on src/plugins/tests.jl
> +        """[1:end-1]
(updated formatting for moving the test above the space for additional tests---see test for example of updated formatting)

2023-08-19 04:23 UTC, hannahilea commented on src/plugins/tests.jl
> +    end
```suggestion
    end
    _validate_aqua_version(p.aqua_version)
```

and then outside this function:
```
_validate_aqua_version(::Nothing) = nothing
_validate_aqua_version(::VersionNumber) = nothing
function _validate_aqua_version(v::AbstractString)
    v == "*" || throw(ArgumentError("Aqua version must be `VersionNumber`, `"*"` for the latest version of Aqua.jl, or `nothing` to skip use of Aqua."
    return nothing
end

```

2023-08-19 04:23 UTC, hannahilea commented on src/plugins/tests.jl
> +    if p.aqua
```suggestion
    if !isnothing(p.aqua_version)
```

2023-08-19 04:23 UTC, hannahilea commented on src/plugins/tests.jl
> +    if p.aqua
```suggestion
    if !isnothing(p.aqua_version)
```

2023-08-19 04:23 UTC, hannahilea commented on src/plugins/tests.jl
> +    if p.aqua
```suggestion
    if !isnothing(p.aqua_version)
```

2023-08-19 04:23 UTC, hannahilea commented on test/show.jl
> +                  aqua: false
```suggestion
                  aqua_version: nothing
```

2023-08-19 04:23 UTC, hannahilea commented on src/plugins/tests.jl
> +        d["AQUA_IMPORT"] = ", Aqua"
(adds imports on separate lines)

2023-08-28 15:29 UTC, gdalle commented on src/plugins/tests.jl
> +    aqua::Bool = false
Interesting workaround! But I'm afraid that if we're too strict, it might freeze Aqua in the version specified by the user when PkgTemplates was called, instead of letting it update to the latest available release.
I'll read the rest of your comments and come back to this one

2023-08-28 15:51 UTC, gdalle commented on src/plugins/tests.jl
> +function make_test_project(p::Tests, pkg_dir::AbstractString)
agreed

2023-08-28 15:51 UTC, gdalle commented on src/plugins/tests.jl
> +function add_test_dependency(p::Tests, pkg_dir::AbstractString)
yep

2023-08-28 15:52 UTC, gdalle commented on test/fixtures/WackyOptions/test/runtests.jl
> +    @testset verbose = true "Code quality (Aqua.jl)" begin
okay

2023-08-28 15:58 UTC, gdalle commented on src/plugins/tests.jl
> +    aqua::Bool = false
okay this works with the `"*"` option

2023-08-28 16:13 UTC, gdalle commented on src/plugins/tests.jl
> +        with_project(() -> Pkg.add(AQUA_DEP), joinpath(pkg_dir, "test"))
good one

2023-08-28 16:31 UTC, gdalle commented
@hannahilea thanks for the feedback, I took your suggestions into account... but it still wasn't enough.

With the new `aqua_version` field, we control the specific version of Aqua that is installed into our test `Manifest.toml`, but we do not control the specific versions of _Aqua's dependencies_. This is why the reference tests fail due to a new version of the [Compat](https://github.com/JuliaLang/Compat.jl) package, on which Aqua depends. Not sure how to deal with that.

2023-08-28 16:34 UTC, hannahilea commented
> With the new aqua_version field, we control the specific version of Aqua that is installed into our test Manifest.toml, but we do not control the specific versions of Aqua's dependencies. This is why the reference tests fail due to a new version of the [Compat](https://github.com/JuliaLang/Compat.jl) package, on which Aqua depends. Not sure how to deal with that.

oof, brutal.  😂 okay, let me think about it a bit more...

2023-08-28 16:59 UTC, hannahilea commented
Okay. So I think the reference tests are important enough that we shouldn't remove them, so what if we:
1. don't test aqua in the "Wacky" test at all (set it to `nothing`---or `false`, if you'd prefer to revert back to the version-less Aqua)
2. added separate tests for the added aqua functionality, and specifically don't test the manifest for those?

2023-08-28 20:05 UTC, gdalle commented
The thing is, I'm planning to add other things to the test template, like JuliaFormatter or JET. So we'll face that problem again soon. Duplicated because we also need to test the "extras" method for test dependencies. 
Im not sure why it is so crucial to include manifests in the reference tests? Why aren't projects enough?

2023-08-29 11:42 UTC, gdalle commented
By the way, it's probably also the Manifest testing that forces us to only run reference tests on a fixed Julia version (1.7.2), which is kind of bizarre.

2023-08-29 14:41 UTC, hannahilea commented
> Im not sure why it is so crucial to include manifests in the reference tests? Why aren't projects enough?

Yeah, that's a good point, and I think I agree that removing manifests is probably the right call. Maybe projects _are_ enough! I haven't contributed enough to this package to make that decision; maybe @nickrobinson251 has an opinion (or could point us to someone who does)?

2023-08-29 14:52 UTC, gdalle commented
If we do get rid of them manifests (probably best done in a separate PR), I think I'll roll back your changes regarding the aqua version to simplify user experience

2023-08-29 14:55 UTC, hannahilea commented
yeah, i agree---no need to specify version there if we don't actually need it.

2023-08-29 14:56 UTC, hannahilea commented
(wish i'd thought about the full set of dependencies in the manifest before sending us down this path---ah well, next time i'll know better!)

2023-09-01 14:52 UTC, gdalle commented
@hannahilea I think we're good to ship this

2023-09-01 14:57 UTC, hannahilea approved these changes
Agreed!

2023-09-01 15:11 UTC, merged